// One-time bootstrap content for the "acil-yaklasimlar" (Yetişkin Algoritmalar)
// category — image-only reference cards from the T.C. Sağlık Bakanlığı adult
// prehospital algorithm set. See api/_lib/db.ts's ensureSchema() for how this
// is applied (automatically, once, the first time the database is used).
export const ACIL_YAKLASIMLAR_INITIAL_TOPICS: { title: string; image: string }[] = [
  { title: "Olay Yeri Yönetimi", image: "olay-yeri-yonetimi" },
  { title: "Acil Olgu Yönetimi Anahtar Noktalar", image: "acil-olgu-yonetimi-anahtar-noktalar" },
  { title: "Acil Olgu Yönetimi", image: "acil-olgu-yonetimi" },
  { title: "Hava Yolu Tıkanıklıkları", image: "hava-yolu-tikanikliklari" },
  { title: "KOAH Anahtar Noktalar", image: "koah-anahtar-noktalar" },
  { title: "KOAH", image: "koah" },
  { title: "Astım Anahtar Noktalar", image: "astim-anahtar-noktalar" },
  { title: "Astım", image: "astim" },
  { title: "Akut Koroner Sendrom Anahtar Noktalar", image: "akut-koroner-sendrom-anahtar-noktalar" },
  { title: "Akut Koroner Sendrom", image: "akut-koroner-sendrom" },
  { title: "Bradikardi Anahtar Noktalar", image: "bradikardi-anahtar-noktalar" },
  { title: "Bradikardi", image: "bradikardi" },
  { title: "Nabızlı Taşikardi", image: "nabizli-tasikardi" },
  { title: "Arrest Yönetimi", image: "arrest-yonetimi" },
  { title: "Şoklanamaz Ritim Yönetimi Anahtar Noktalar", image: "soklanamaz-ritim-yonetimi-anahtar-noktalar" },
  { title: "Şoklanamaz Ritim Yönetimi: Asistoli / NEA", image: "soklanamaz-ritim-yonetimi-asistoli-nea" },
  {
    title: "Şoklanır Ritim Yönetimi VF / Nabızsız VT Anahtar Noktalar",
    image: "soklanir-ritim-yonetimi-vf-nabizsiz-vt-anahtar-noktalar",
  },
  { title: "Şoklanır Ritim Yönetimi: VF / Nabızsız VT", image: "soklanir-ritim-yonetimi-vf-nabizsiz-vt" },
  { title: "Resüsitasyon Sonrası Bakım", image: "resusitasyon-sonrasi-bakim" },
  { title: "Hipovolemik Şok", image: "hipovolemik-sok" },
  {
    title: "Akut Akciğer Ödemi ve Kardiyojenik Şok Anahtar Noktalar",
    image: "akut-akciger-odemi-ve-kardiyojenik-sok-anahtar-noktalar",
  },
  {
    title: "Kalp Yetmezliğine Bağlı Akut Akciğer Ödemi ve Kardiyojenik Şok",
    image: "kalp-yetmezligine-bagli-akut-akciger-odemi-ve-kardiyojenik-sok",
  },
  { title: "Ajite Hastaya Yaklaşım Anahtar Noktalar", image: "ajite-hastaya-yaklasim-anahtar-noktalar" },
  { title: "Ajite Hastaya Yaklaşım", image: "ajite-hastaya-yaklasim" },
  { title: "Bilinç Değişiklikleri Anahtar Noktalar", image: "bilinc-degisiklikleri-anahtar-noktalar" },
  { title: "Bilinç Değişikliği", image: "bilinc-degisikligi" },
  { title: "Diyabetik Aciller", image: "diyabetik-aciller" },
  { title: "İnme / SVO", image: "i-nme-svo" },
  { title: "Nöbet / Konvülziyon", image: "nobet-konvulziyon" },
  { title: "Vertigo", image: "vertigo" },
  { title: "Alerjik Reaksiyon", image: "alerjik-reaksiyon" },
  { title: "Anafilaksi Anahtar Noktalar", image: "anafilaksi-anahtar-noktalar" },
  { title: "Anafilaksi", image: "anafilaksi" },
  { title: "Hipertermi Anahtar Noktalar", image: "hipertermi-anahtar-noktalar" },
  { title: "Hipertermi", image: "hipertermi" },
  { title: "Hipotermi Anahtar Noktalar", image: "hipotermi-anahtar-noktalar" },
  { title: "Hipotermi", image: "hipotermi" },
  { title: "Hipotermide Arrest Yönetimi Anahtar Noktalar", image: "hipotermide-arrest-yonetimi-anahtar-noktalar" },
  { title: "Hipotermide Arrest Yönetimi", image: "hipotermide-arrest-yonetimi" },
  { title: "Isırma ve Sokmalar Anahtar Noktalar", image: "isirma-ve-sokmalar-anahtar-noktalar" },
  { title: "Isırma ve Sokmalar", image: "isirma-ve-sokmalar" },
  { title: "Suda Boğulma Anahtar Noktalar", image: "suda-bogulma-anahtar-noktalar" },
  { title: "Suda Boğulma", image: "suda-bogulma" },
  { title: "Yanık Anahtar Noktalar (Sıvı ve Transfer)", image: "yanik-anahtar-noktalar-sivi-ve-transfer" },
  { title: "Yanık Anahtar Noktalar (Vücut Yüzey Alanı)", image: "yanik-anahtar-noktalar-vucut-yuzey-alani" },
  { title: "Termal Yanık", image: "termal-yanik" },
  { title: "Elektrik Yanıkları", image: "elektrik-yaniklari" },
  { title: "Kimyasal Yanıklar", image: "kimyasal-yaniklar" },
  { title: "Zehirlenmelere Genel Yaklaşım Anahtar Noktalar", image: "zehirlenmelere-genel-yaklasim-anahtar-noktalar" },
  { title: "Zehirlenmelere Genel Yaklaşım", image: "zehirlenmelere-genel-yaklasim" },
  { title: "Yüksek Doz İlaç Alımı", image: "yuksek-doz-i-lac-alimi" },
  { title: "Karbonmonoksit Zehirlenmesi", image: "karbonmonoksit-zehirlenmesi" },
  {
    title: "Kalsiyum Kanal Blokerleri / Beta Blokerlerle Zehirlenme Anahtar Noktalar",
    image: "kalsiyum-kanal-blokerleri-beta-blokerlerle-zehirlenme-anahtar-noktalar",
  },
];
